export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Work} from './project/Work'
export {default as Skills} from './skills/Skills'
export {default as Footer} from './footer/Footer'